const PDFDocument = require("pdfkit");

const generatePredictionPDF = (name, input, result) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.rect(0, 0, doc.page.width, 80).fill("#4f46e5");
    doc.fillColor("#ffffff").fontSize(22).text("EduPredict AI – Prediction Report", 50, 25, { align: "center" });

    doc.moveDown(3).fillColor("#1f2937");

    // Student Info
    doc.fontSize(14).text(`Student: ${name}`);
    doc.fontSize(11).fillColor("#6b7280").text(`Generated: ${new Date().toLocaleString()}`);

    doc.moveDown().strokeColor("#e5e7eb").lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Results Section
    doc.fillColor("#4f46e5").fontSize(13).text("Prediction Results");
    doc.moveDown(0.5).fillColor("#1f2937").fontSize(11);
    doc.text(`Predicted Marks       : ${result.predictedMarks}`);
    doc.text(`Performance Category  : ${result.performanceCategory}`);
    doc.text(`Suggested Career      : ${result.predictedCareer}`);
    doc.text(`Career Confidence     : ${result.careerConfidence}%`);
    doc.text(`Interest Area         : ${result.mappedInterest}`);

    doc.moveDown();
    doc.strokeColor("#e5e7eb").lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Input Data Section
    doc.fillColor("#4f46e5").fontSize(13).text("Input Data");
    doc.moveDown(0.5).fillColor("#1f2937").fontSize(11);
    doc.text(`Study Hours           : ${input.studyHours}`);
    doc.text(`Attendance            : ${input.attendance}%`);
    doc.text(`Previous Marks        : ${input.previousMarks}`);
    doc.text(`Programming Skill     : ${input.programmingSkill} / 3`);
    doc.text(`Communication Skill   : ${input.communicationSkill} / 3`);
    doc.text(`Interest Area         : ${input.interestArea}`);

    doc.moveDown();
    doc.strokeColor("#e5e7eb").lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Weak Areas
    if (result.weakAreas && result.weakAreas.length) {
      doc.fillColor("#4f46e5").fontSize(13).text("Weak Areas");
      doc.moveDown(0.5).fillColor("#1f2937").fontSize(11);
      result.weakAreas.forEach((area) => doc.text(`• ${area}`));
      doc.moveDown();
    }

    // Recommendations
    if (result.recommendations && result.recommendations.length) {
      doc.fillColor("#4f46e5").fontSize(13).text("Recommendations");
      doc.moveDown(0.5).fillColor("#1f2937").fontSize(11);
      result.recommendations.forEach((rec) => doc.text(`• ${rec}`));
      doc.moveDown();
    }

    // Footer
    doc.strokeColor("#e5e7eb").lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5).fillColor("#9ca3af").fontSize(10)
      .text("This report was auto-generated by EduPredict AI. For educational purposes only.", { align: "center" });

    doc.end();
  });
};

module.exports = { generatePredictionPDF };
